# Generated by Django 6.0.3 on 2026-03-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='savedword',
            old_name='created_at',
            new_name='added_at',
        ),
        migrations.RemoveField(
            model_name='savedword',
            name='context_sentence',
        ),
        migrations.RemoveField(
            model_name='savedword',
            name='source_url',
        ),
        migrations.RemoveField(
            model_name='savedword',
            name='status',
        ),
        migrations.AddField(
            model_name='savedword',
            name='turkish_meaning',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='savedword',
            name='language',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='savedword',
            name='word',
            field=models.CharField(max_length=100),
        ),
    ]
