# Generated by Django 6.0.3 on 2026-04-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocabulary', '0002_rename_created_at_savedword_added_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedword',
            name='status',
            field=models.CharField(choices=[('learning', 'Öğreniyorum ⏳'), ('review', 'Tekrar Et 🔄'), ('learned', 'Öğrendim ✅')], default='learning', max_length=20),
        ),
        migrations.AddField(
            model_name='savedword',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
